-- Fix: Remove team_name_normalized from INSERT statement
-- It's a GENERATED ALWAYS column and cannot be inserted manually

CREATE OR REPLACE FUNCTION public.approve_registration(
  reg_id uuid,
  admin_user_id uuid,
  notes text DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  reg_record record;
  new_team_id uuid;
BEGIN
  -- Fetch the registration record (must be pending)
  SELECT * INTO reg_record
  FROM public.registration_meta
  WHERE id = reg_id AND status = 'pending';
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Registration not found or not pending: %', reg_id;
  END IF;
  
  -- Route to appropriate team table based on event_type
  IF reg_record.event_type = 'tn' THEN
    -- Insert into team_meta for TN
    -- REMOVED team_name_normalized from column list (it's GENERATED ALWAYS)
    INSERT INTO public.team_meta (
      user_id, season, category, division_code, option_choice,
      team_code, team_name, org_name, org_address,
      team_manager_1, mobile_1, email_1,
      team_manager_2, mobile_2, email_2,
      team_manager_3, mobile_3, email_3,
      registration_id
    ) VALUES (
      reg_record.user_id, reg_record.season, reg_record.category, reg_record.division_code, reg_record.option_choice,
      reg_record.team_code, reg_record.team_name, reg_record.org_name, reg_record.org_address,
      reg_record.team_manager_1, reg_record.mobile_1, reg_record.email_1,
      reg_record.team_manager_2, reg_record.mobile_2, reg_record.email_2,
      reg_record.team_manager_3, reg_record.mobile_3, reg_record.email_3,
      reg_record.id
    ) RETURNING id INTO new_team_id;
    
  ELSIF reg_record.event_type = 'wu' THEN
    -- Insert into wu_team_meta for WU (team_code will be auto-generated by trigger)
    INSERT INTO public.wu_team_meta (
      user_id, season, division_code,
      team_code, team_name,
      package_choice, team_size,
      team_manager, mobile, email,
      org_name, org_address,
      registration_id
    ) VALUES (
      reg_record.user_id, reg_record.season, reg_record.division_code,
      '', reg_record.team_name,  -- Empty team_code will trigger auto-generation
      reg_record.package_choice, reg_record.team_size,
      reg_record.team_manager_1, reg_record.mobile_1, reg_record.email_1,
      reg_record.org_name, reg_record.org_address,
      reg_record.id
    ) RETURNING id INTO new_team_id;
    
  ELSIF reg_record.event_type = 'sc' THEN
    -- Insert into sc_team_meta for SC (team_code will be auto-generated by trigger)
    INSERT INTO public.sc_team_meta (
      user_id, season, division_code,
      team_code, team_name,
      package_choice, team_size,
      team_manager, mobile, email,
      org_name, org_address,
      registration_id
    ) VALUES (
      reg_record.user_id, reg_record.season, reg_record.division_code,
      '', reg_record.team_name,  -- Empty team_code will trigger auto-generation
      reg_record.package_choice, reg_record.team_size,
      reg_record.team_manager_1, reg_record.mobile_1, reg_record.email_1,
      reg_record.org_name, reg_record.org_address,
      reg_record.id
    ) RETURNING id INTO new_team_id;
    
  ELSE
    RAISE EXCEPTION 'Unknown event_type: %', reg_record.event_type;
  END IF;
  
  -- Mark registration as approved
  UPDATE public.registration_meta
  SET status = 'approved',
      approved_by = admin_user_id,
      approved_at = now(),
      admin_notes = notes
  WHERE id = reg_id;
  
  RETURN new_team_id;
END;
$$;


