-- Test data setup for admin system testing
-- Run this SQL script in your Supabase SQL editor or via psql

-- Insert 3 test rows into registration_meta with status='pending'

-- 1. TN/L=ladies (Traditional / Ladies division)
INSERT INTO public.registration_meta (
  season,
  event_type,
  category,
  division_code,
  option_choice,
  team_code,
  team_name,
  org_name,
  org_address,
  team_manager_1,
  mobile_1,
  email_1,
  team_manager_2,
  mobile_2,
  email_2,
  status
) VALUES (
  2025,
  'tn',
  'ladies_open',
  'L',
  'Option 1',
  'S25-L001',  -- For TN, we can provide the code as it matches single-letter pattern
  'Test Ladies Team',
  'Test Organization',
  '123 Test Street, Test City',
  'Manager One',
  '1234567890',
  'manager1@test.com',
  'Manager Two',
  '0987654321',
  'manager2@test.com',
  'pending'
);

-- 2. WU/WX (Warm-Up / Mixed division)
-- Note: Let trigger auto-generate team_code by setting it to NULL or empty
-- The trigger uses the full division_code ('WX'), so the pattern will be S25-WX###
INSERT INTO public.registration_meta (
  season,
  event_type,
  division_code,
  team_code,  -- Will be auto-generated by trigger (pattern: S25-WX###)
  team_name,
  package_choice,
  team_size,
  team_manager_1,
  mobile_1,
  email_1,
  team_manager_2,
  mobile_2,
  email_2,
  org_name,
  org_address,
  status
) VALUES (
  2025,
  'wu',
  'WX',  -- Full division code - trigger will use this for prefix
  NULL,  -- NULL - trigger will auto-generate with pattern S25-WX###
  'Test WU Mixed Team',
  'basic_wu',
  20,
  'WU Manager One',
  '1112223333',
  'wu_manager1@test.com',
  'WU Manager Two',
  '4445556666',
  'wu_manager2@test.com',
  'WU Test Org',
  '456 WU Street',
  'pending'
);

-- 3. SC/SM (Sprint Challenge / Men division)
-- Note: Let trigger auto-generate team_code by setting it to NULL or empty
-- The trigger uses the full division_code ('SM'), so the pattern will be S25-SM###
INSERT INTO public.registration_meta (
  season,
  event_type,
  division_code,
  team_code,  -- Will be auto-generated by trigger (pattern: S25-SM###)
  team_name,
  package_choice,
  team_size,
  team_manager_1,
  mobile_1,
  email_1,
  team_manager_2,
  mobile_2,
  email_2,
  org_name,
  org_address,
  status
) VALUES (
  2025,
  'sc',
  'SM',  -- Full division code - trigger will use this for prefix
  NULL,  -- NULL - trigger will auto-generate with pattern S25-SM###
  'Test SC Men Team',
  'premium_sc',
  15,
  'SC Manager One',
  '7778889999',
  'sc_manager1@test.com',
  'SC Manager Two',
  '1011121314',
  'sc_manager2@test.com',
  'SC Test Org',
  '789 SC Street',
  'pending'
);

-- Verification queries
-- Check that 3 pending rows exist
SELECT 
  id,
  event_type,
  division_code,
  team_name,
  team_code,
  status,
  created_at
FROM public.registration_meta
WHERE status = 'pending'
ORDER BY created_at DESC;

