/**
 * Auto-generated TypeScript types from OpenAPI specification
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is generated from docs/openapi.yaml
 * 
 * To regenerate:
 *   npm run generate:api-types
 * 
 * Last generated: $(date)
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/public/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new team
         * @description Submit a new team registration. This endpoint is public and does not require authentication.
         */
        post: operations["registerTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a registration
         * @description Approve a pending registration. Requires admin authentication and CSRF token.
         */
        post: operations["approveRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a registration
         * @description Reject a pending registration. Requires admin authentication, CSRF token, and rejection notes.
         */
        post: operations["rejectRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List registrations
         * @description Get a paginated list of registrations with filtering and search. Requires admin authentication.
         */
        get: operations["listRegistrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/counters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get registration counters
         * @description Get counts of registrations by status and new registrations today. Requires admin authentication.
         */
        get: operations["getCounters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export team data as CSV
         * @description Export team data for a specific mode and optional filters. Requires admin authentication and CSRF token.
         */
        post: operations["exportData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/csrf-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get CSRF token
         * @description Get a CSRF token for state-changing requests. The token is also set in a cookie.
         */
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegistrationRequest: {
            /**
             * @description Race category
             * @enum {string}
             */
            race_category: "men_open" | "ladies_open" | "mixed_open" | "mixed_corporate";
            /** @description Total number of teams */
            num_teams: number;
            /** @description Number of teams choosing Option 1 */
            num_teams_opt1: number;
            /** @description Number of teams choosing Option 2 */
            num_teams_opt2: number;
            /** @description Season year */
            season: number;
            /** @description Organization name */
            org_name: string;
            /** @description Organization address (optional) */
            org_address?: string;
            /** @description Array of team names */
            team_names: string[];
            /** @description Array of team options (must match team_names length) */
            team_options: ("Option 1" | "Option 2")[];
            managers: components["schemas"]["Managers"];
        };
        Managers: {
            manager1_name: string;
            manager1_mobile?: string;
            /** Format: email */
            manager1_email?: string;
            manager2_name: string;
            manager2_mobile?: string;
            /** Format: email */
            manager2_email?: string;
            manager3_name?: string;
            manager3_mobile?: string;
            /** Format: email */
            manager3_email?: string;
        };
        RegistrationResponse: {
            /** Format: uuid */
            registration_id?: string;
            teams?: {
                /** Format: uuid */
                id?: string;
                /** @example S25-M001 */
                team_code?: string;
            }[];
        };
        ApproveRequest: {
            /**
             * Format: uuid
             * @description UUID of the registration to approve
             */
            registration_id: string;
            /** @description Optional approval notes */
            notes?: string;
        };
        ApproveResponse: {
            /** @example true */
            ok?: boolean;
            /**
             * Format: uuid
             * @description ID of the created team_meta record
             */
            team_meta_id?: string;
        };
        RejectRequest: {
            /**
             * Format: uuid
             * @description UUID of the registration to reject
             */
            registration_id: string;
            /** @description Rejection notes (required) */
            notes: string;
        };
        RejectResponse: {
            /** @example true */
            ok?: boolean;
        };
        ListResponse: {
            /** @example true */
            ok?: boolean;
            /** @description Current page number */
            page?: number;
            /** @description Number of items per page */
            pageSize?: number;
            /** @description Total number of items */
            total?: number;
            items?: components["schemas"]["RegistrationItem"][];
        };
        RegistrationItem: {
            /** Format: uuid */
            id?: string;
            season?: number;
            /** @enum {string} */
            event_type?: "tn" | "wu" | "sc";
            division_code?: string;
            category?: string;
            /** @enum {string} */
            option_choice?: "Option 1" | "Option 2";
            team_code?: string;
            team_name?: string;
            org_name?: string;
            org_address?: string;
            manager_name?: string;
            manager_email?: string;
            manager_mobile?: string;
            /** @enum {string} */
            status?: "pending" | "approved" | "rejected";
            /** Format: uuid */
            approved_by?: string | null;
            /** Format: date-time */
            approved_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        CountersResponse: {
            /** @example true */
            ok?: boolean;
            /** @description Total number of registrations */
            total?: number;
            /** @description Number of pending registrations */
            pending?: number;
            /** @description Number of approved registrations */
            approved?: number;
            /** @description Number of rejected registrations */
            rejected?: number;
            /** @description Number of new registrations today */
            new_today?: number;
        };
        ExportRequest: {
            /**
             * @description Export mode
             * @enum {string}
             */
            mode: "tn" | "wu" | "sc" | "all";
            /** @description Filter by season (optional) */
            season?: number;
            /**
             * @description Filter by category (optional, only for TN mode)
             * @enum {string}
             */
            category?: "men_open" | "ladies_open" | "mixed_open" | "mixed_corporate";
        };
        CsrfTokenResponse: {
            /** @example true */
            ok?: boolean;
            /** @description CSRF token to include in X-CSRF-Token header */
            token?: string;
        };
        ErrorResponse: {
            /** @example false */
            ok?: boolean;
            /** @description Error message */
            error?: string;
            /** @description Error code */
            code?: string;
            /** @description Validation error details (only for 422 errors) */
            detail?: Record<string, never>[];
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "ok": false,
                 *       "error": "Bad request",
                 *       "code": "BAD_REQUEST"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Forbidden - authentication required or insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "ok": false,
                 *       "error": "Forbidden",
                 *       "code": "FORBIDDEN"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "ok": false,
                 *       "error": "Resource not found",
                 *       "code": "NOT_FOUND"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict - resource already processed */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "ok": false,
                 *       "error": "Registration already processed or not found",
                 *       "code": "ALREADY_PROCESSED"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "ok": false,
                 *       "error": "Invalid input",
                 *       "detail": [
                 *         {
                 *           "path": [
                 *             "registration_id"
                 *           ],
                 *           "message": "Invalid uuid"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "ok": false,
                 *       "error": "Internal server error",
                 *       "code": "INTERNAL_ERROR"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationRequest"];
            };
        };
        responses: {
            /** @description Registration created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "registration_id": "550e8400-e29b-41d4-a716-446655440000",
                     *       "teams": [
                     *         {
                     *           "id": "660e8400-e29b-41d4-a716-446655440001",
                     *           "team_code": "S25-M001"
                     *         },
                     *         {
                     *           "id": "660e8400-e29b-41d4-a716-446655440002",
                     *           "team_code": "S25-M002"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["RegistrationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    approveRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "registration_id": "550e8400-e29b-41d4-a716-446655440000",
                 *       "notes": "Approved after review"
                 *     }
                 */
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Registration approved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ok": true,
                     *       "team_meta_id": "660e8400-e29b-41d4-a716-446655440001"
                     *     }
                     */
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    rejectRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "registration_id": "550e8400-e29b-41d4-a716-446655440000",
                 *       "notes": "Incomplete information provided"
                 *     }
                 */
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Registration rejected successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ok": true
                     *     }
                     */
                    "application/json": components["schemas"]["RejectResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listRegistrations: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Number of items per page (max 100) */
                pageSize?: number;
                /** @description Search term (searches team_name, org_name, email_1, team_code) */
                q?: string;
                /** @description Filter by status */
                status?: "all" | "pending" | "approved" | "rejected";
                /** @description Filter by event type */
                event?: "all" | "tn" | "wu" | "sc";
                /** @description Filter by season (year) */
                season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of registrations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ok": true,
                     *       "page": 1,
                     *       "pageSize": 50,
                     *       "total": 100,
                     *       "items": [
                     *         {
                     *           "id": "550e8400-e29b-41d4-a716-446655440000",
                     *           "season": 2025,
                     *           "event_type": "tn",
                     *           "division_code": "M",
                     *           "category": "men_open",
                     *           "option_choice": "Option 1",
                     *           "team_code": "S25-M001",
                     *           "team_name": "Team Alpha",
                     *           "org_name": "Example Org",
                     *           "status": "pending",
                     *           "created_at": "2025-01-01T00:00:00Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCounters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registration counters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ok": true,
                     *       "total": 150,
                     *       "pending": 25,
                     *       "approved": 100,
                     *       "rejected": 25,
                     *       "new_today": 5
                     *     }
                     */
                    "application/json": components["schemas"]["CountersResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    exportData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description CSV file */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ok": true,
                     *       "token": "abc123.def456"
                     *     }
                     */
                    "application/json": components["schemas"]["CsrfTokenResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
}
