#!/bin/bash
# scripts/generate-api-types.sh
# Generate TypeScript types from OpenAPI specification

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Generating TypeScript types from OpenAPI specification...${NC}"

# Check if openapi-typescript is installed
if ! command -v openapi-typescript &> /dev/null; then
  echo -e "${YELLOW}openapi-typescript not found. Installing...${NC}"
  npm install --save-dev openapi-typescript
fi

# Check if OpenAPI spec exists
if [ ! -f "docs/openapi.yaml" ]; then
  echo -e "${RED}Error: docs/openapi.yaml not found${NC}"
  exit 1
fi

# Generate types
echo -e "${GREEN}Generating types from docs/openapi.yaml...${NC}"
npx openapi-typescript docs/openapi.yaml -o types/api-generated.ts

# Check if generation was successful
if [ $? -eq 0 ]; then
  echo -e "${GREEN}✓ TypeScript types generated successfully at types/api-generated.ts${NC}"
  
  # Add a header comment to the generated file
  cat > types/api-generated.ts.tmp << 'EOF'
/**
 * Auto-generated TypeScript types from OpenAPI specification
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is generated from docs/openapi.yaml
 * 
 * To regenerate:
 *   npm run generate:api-types
 * 
 * Last generated: $(date)
 */

EOF
  cat types/api-generated.ts >> types/api-generated.ts.tmp
  mv types/api-generated.ts.tmp types/api-generated.ts
  
  echo -e "${GREEN}✓ Added header comment to generated file${NC}"
else
  echo -e "${RED}Error: Failed to generate types${NC}"
  exit 1
fi

echo -e "${GREEN}Done!${NC}"

