-- =========================================================
-- FIX: Team Code Generation Timing
-- =========================================================
-- Team codes should ONLY be generated on admin approval,
-- NOT at submission time.
-- =========================================================

-- Step 1: Make team_code nullable in registration_meta
-- (Team codes should only exist after approval)
ALTER TABLE public.registration_meta 
  ALTER COLUMN team_code DROP NOT NULL;

-- Step 2: Remove the CHECK constraint that requires team_code
-- (This constraint prevents NULL values)
ALTER TABLE public.registration_meta 
  DROP CONSTRAINT IF EXISTS registration_meta_team_code_check;

-- Add a new constraint that allows NULL (pending approval)
ALTER TABLE public.registration_meta 
  ADD CONSTRAINT registration_meta_team_code_check 
  CHECK (team_code IS NULL OR length(btrim(team_code)) > 0);

-- Step 3: Update the trigger to NOT generate team codes on insert
-- Team codes will be generated by approve_registration function instead
CREATE OR REPLACE FUNCTION public.registration_meta_normalize_and_assign()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  cat_norm text;
  eff_letter text;
BEGIN
  -- normalize legacy category
  IF NEW.category IS NOT NULL THEN
    NEW.category := replace(lower(btrim(NEW.category)), ' ','_');
  END IF;
  cat_norm := NEW.category;

  -- Normalize team_code if provided, but DON'T generate it
  -- Team codes are generated on approval, not at submission
  IF NEW.team_code IS NOT NULL THEN
    NEW.team_code := upper(btrim(NEW.team_code));
  END IF;
  -- NOTE: Removed team code generation logic - codes are generated on approval

  -- Handle division code based on event type (still needed for other logic)
  IF NEW.event_type = 'tn' THEN
    -- TN: Use first letter of division_code or map from category
    IF NEW.division_code IS NOT NULL AND btrim(NEW.division_code) <> '' THEN
      eff_letter := upper(substring(btrim(NEW.division_code) from 1 for 1));
    ELSE
      eff_letter := public._cat_letter(cat_norm);
    END IF;
  ELSE
    -- WU/SC: Use full division_code prefix from division_config_general
    IF NEW.division_code IS NOT NULL AND btrim(NEW.division_code) <> '' THEN
      eff_letter := upper(btrim(NEW.division_code));
    ELSE
      -- Default fallback based on event type
      IF NEW.event_type = 'wu' THEN
        eff_letter := 'W';
      ELSIF NEW.event_type = 'sc' THEN
        eff_letter := 'S';
      ELSE
        eff_letter := 'T';
      END IF;
    END IF;
  END IF;

  -- Normalize team name for uniqueness constraint
  IF NEW.team_name_en IS NOT NULL THEN
    NEW.team_name_normalized := upper(replace(replace(replace(btrim(NEW.team_name_en), ' ', ''), '-', ''), '_', ''));
  END IF;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.registration_meta_normalize_and_assign IS 
'Normalizes registration_meta data on insert. Team codes are NOT generated here - they are generated on approval.';

-- Step 4: Update the unique constraint to allow multiple NULL team_codes
-- (Multiple pending registrations can have NULL team_code)
-- The existing constraint should already handle this, but verify:
-- CONSTRAINT uniq_registration_teamcode_global UNIQUE (team_code);
-- PostgreSQL UNIQUE constraints allow multiple NULL values, so this is fine.

-- Step 5: Add comment to team_code column
COMMENT ON COLUMN public.registration_meta.team_code IS 
'Team code (e.g., S26-M001). Generated on admin approval, NULL until approved.';

-- Step 6: Verify the approve_registration function generates team codes
-- (This should already exist, but we'll check it exists)
-- If it doesn't exist, it needs to be created to generate team codes on approval


